use zip for image download as default
bit-bots/imagetagger pull request #177
Opened 2020-12-12 16:57 UTC by johagge

Currently the images are downloaded individually by default. This is slow.
This pull request replaces this behavior by downloading the zip file for the imageset instead. This works significantly faster (in my experiments).

Currently the other method for downloading is still included in the download script, in case the zip download does not work. This way it is just a single line to replace to go back to the previous behavior.

2020-12-12 23:52 UTC, NFiedler requested changes

2020-12-12 23:52 UTC, NFiedler commented on imagetagger/imagetagger/images/templates/images/download.py
> +csrfmiddlewaretoken = csrftoken
this is a bit unneccessary.

2020-12-17 15:51 UTC, johagge commented on imagetagger/imagetagger/images/templates/images/download.py
> +csrfmiddlewaretoken = csrftoken
I changed it to be less redundant

2020-12-17 17:59 UTC, johagge commented
The script currently does not check if an imageset has a zip already. There should be some error handling for that case, e.g. a warning that either the imageset or zip does not exist.

2020-12-24 15:58 UTC, johagge commented
I added error handling, but was not able to test it for a non existing zip file, because I currently do not have an development environment of the ImageTagger.
I also made it possible to use the old version of separately downloading each image.

2021-01-01 14:57 UTC, timonegk commented
I tested the script for non-existing zip files and fixed a few minor things. Looks good now.

2021-01-01 14:57 UTC, timonegk approved these changes

2021-01-01 14:58 UTC, merged